_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.6
            "5": 0.19.5
            "6": 4.55.0
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
ch_estimation:
    value:
        cond:
            in_channels: 2
            length: 3072
            step_size: 12
            steps_per_token: 1
        transformer:
            activation: relu
            channels: 2
            d_model: 128
            dim_feedforward: 1024
            dropout: 0.1
            length: 3072
            n_head: 8
            n_token: 256
            num_layers: 4
dataset:
    value:
        batch_size: 32
        carrier_freq: 28
        channel_type:
            - InF_Los
            - InF_Nlos
            - InH_Los
            - InH_Nlos
            - RMa_Los
            - RMa_Nlos
            - UMa_Los
            - UMa_Nlos
            - UMi_Los
            - UMi_Nlos
        cp_length: 590
        distance_range:
            - 10
            - 500
        fft_size: 4096
        is_channel: true
        is_noise: true
        is_phase_noise: false
        max_random_tap_delay_cp_proportion: 0.2
        mod_order: 64
        noise_spectral_density: -174
        num_guard_subcarriers: 1024
        num_symbol: 14
        num_workers: 0
        ref_conf_dict:
            dmrs:
                - 0
                - 3072
                - 6
        rnd_seed: 0
        subcarrier_spacing: 120
        transmit_power: 30
training:
    value:
        ch_loss_weight: 1
        device: cuda:0
        evaluation_batch_size: 4
        evaluation_step: 5000
        load_model_path: ""
        logging_step: 100
        lr: 0.0001
        max_norm: 1
        model_save_step: 10000
        momentum: 0.9
        num_iter: 200000
        num_warmup_steps: 1000
        optimizer: Adam
        pn_train_start_iter: 50000
        saved_model_name: Large_estimator_v4_base
        use_scheduler: true
        use_wandb: true
        wandb_proj: DNN_channel_estimation_v4_base
        weight_decay: 1e-06
